### ISSUE TITLE
Pass `dragState` to `onX` callbacks

### ISSUE THREAD

**Issue by sisp** [chrisjpatty/react-dragtastic#28]
I need to access attributes of `dragState` in some of the callbacks, e.g. `onDrop`, but the callbacks either receive no arguments or `dragState.data`. Would you be open to passing `dragState` to all `onX` callbacks?

**Comment by chrisjpatty** [comment]
Ah, great idea. Yeah it would definitely make sense for the callbacks to receive the state. I'll add this issue to the roadmap.

**Comment by boghsteren** [comment]
Has this been released in the version that's currently on NPM? It doesn't look like it?

Are you still maintaining this package? I really like the simplicity and flexibility of it and have a few suggestions on how to improve it.
